version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./docker_config.py:/code/project/default_config.py
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRESS_DB: users
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5