TOKEN_EXPIRE_MINUTES = 15
TOKEN_EXPIRE_DAYS = 130
JWT_ALGORITHM = "HS256"
JWT_SECRET = "j16unPMvd3oWw1G32oVcwHdjivzaYx3DGGJVfW81sEiApqnKVF6PrSWaPptU1C"
UPLOAD_FOLDER = "./project/frontend/static/uploads"
ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg"}
SALT = b'ivzaYx31G32oVc3oWw1G32'
